name: Cypress Pipeline

on:
  push:
    branches: [ "main" ]           # run on every commit to main
  pull_request:
    branches: [ "main" ]           # and on PRs targeting main
  schedule:
    - cron: "0 6 * * *"            # daily at 06:00 UTC


jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

